import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  dataContainer: {
    marginBottom: 10,
  },
  unselectedPicker: {
    opacity: 0.2
  },
  zeroTricks: {
    marginLeft: 10
  },
  dataText: {
    fontWeight: 'bold',
    fontSize: 16,
  },
  deleteButton: {
    position: 'absolute',
    right: 1, 
    padding: 10,
    marginLeft: 10,
    borderRadius: 5,
  },
  deleteButtonText: {
    color: 'red',
    fontWeight: 'bold',
  },
  resultsCell: {
    flex: 3,
    paddingHorizontal: 5,
    textAlign: 'center',
  },
  buttonContainer: {
    flexDirection: 'row',
    width: 200,
    marginLeft: 40,
    flexWrap: 'wrap',
    justifyContent: 'center',
    borderRadius: 20,
    shadowColor: '#181E25',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  button: {
    backgroundColor: 'white',
    justifyContent: 'center', 
    alignItems: 'center', 
    margin: 10,
    borderWidth: 1,
    borderColor: '#077794',
    borderRadius: 15, 
    width: 80, 
    height: 80,
  },
  buttonText: {
    color: 'black',
    textAlign: 'center',
    fontSize: 20,
  },
  message: {
    textAlign: 'center',
    marginBottom: 20,
    color: '#022657', 
    fontFamily: 'Nexa', 
    fontSize: 22, 
    fontWeight: '800', 
    fontStyle: 'normal', 
    lineHeight: 24,
  },
  selectedParameter: {
    backgroundColor: '#029DB7',
  },
  selectedButton: {
    // Ajout de styles si nécessaire
  },
  inputGame: {
    height: 40,
    width: 240,
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 10,
    paddingHorizontal: 10,
    justifyContent: 'center',
    // textAlign: 'center',
    marginLeft: 65,
    borderRadius: 10,
    color: 'black',
  },
  gameItem: {
    fontSize: 18,
    padding: 10,
    
  },
  gameItemContainer: {
    flexDirection: 'row',
    paddingVertical: 8,
    paddingHorizontal: 8,
    alignItems: 'center',
    alignSelf: 'stretch',
    borderRadius: 16,
    backgroundColor: '#F9FAFB',
    shadowColor: '#181E25', 
    shadowOffset: { width: 0, height: 1 }, 
    shadowOpacity: 0.2, 
    shadowRadius: 2,
    marginBottom: 10
  },

  navigationButton: {
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'black',
    marginBottom: 10,
  },
  navigationButtons: {
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: 10,
  },
  cancelButton: {
    backgroundColor: 'white',
    padding: 10,
    margin: 5,
    borderRadius: 10, 
    alignItems: 'center',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContainer: {
    width: 300,
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10, 
    alignItems: 'center',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  gameName: {
    color: '#022657',
    fontFamily: 'Nexa', 
    fontSize: 18, 
    fontWeight: '800', 
    fontStyle: 'normal',
    lineHeight: 24,
    alignSelf: 'stretch',
  },
  gameBoards: {
    flex: 1,
    color: '#5D6D7D', 
    fontFamily: 'Nexa', 
    fontSize: 15, 
    fontWeight: '800', 
    fontStyle: 'normal', 
    lineHeight: 24, 
    alignSelf: 'stretch',
  },
  icon: {
    width: 100,
    height: 100
  },
  gameManagementContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },
  gameDetailsContainer: {
    flex: 1
  },
  pickerContainer: {
    flex: 1,
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
  },
  currentGameText: {
    color: '#022657',
    fontFamily: 'Nexa', 
    fontSize: 18, 
    fontWeight: '800', 
    fontStyle: 'normal', 
    lineHeight: 24,
    textAlign: 'center',
    marginBottom: 10,
    marginLeft: 10
  },
  layoutstyle: {
    width: 375,
    height: 130,
    flexShrink: 0,
  },
  buttonTextBack: {
    justifyContent: 'center',
    alignItems: 'center',
    color: 'black',
    fontSize: 17,
    width: 115,
    padding: 10, 
    borderRadius: 10, 
  },
  buttonTextNext: {
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    color: 'white',
    fontSize: 19,
    width: 110, 
    height: 43,
    padding: 10, 
    borderRadius: 10,
  },
  spaceBetweenButtons: {
    marginHorizontal: 10, 
  },
  nextButton: {
    backgroundColor: '#029DB7', 
  },
  buttonTextCancel: {
    textDecorationLine: 'underline', 
    marginBottom: 10,
    marginLeft: 40
  },
  tricksButton: {
    backgroundColor: 'white',
    padding: 20,
    marginVertical: 10,
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: '#077794',
    borderRadius: 10,
    alignItems: 'center',
    width: 150, 
    height: 70, 
  },
  tricksButtonContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    marginLeft: 40,
    justifyContent: 'center',
  },
    SelectedTricksButton: {
    backgroundColor: '#029DB7',
  },
  buttoncreate: {
    marginLeft: 200,
    marginTop: 10,
    backgroundColor: '#029DB7',
    borderWidth: 0,
    borderRadius: 20,
    color: 'white',
    shadowColor: '#029DB7',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 2,
  },
  messagepartie: {
    color: '#022657', 
    fontFamily: 'Nexa', 
    fontSize: 18, 
    fontWeight: '800', 
    fontStyle: 'normal', 
    lineHeight: 24,
    marginLeft: 10
  },
  sectionContainer: {
    paddingVertical: 12,
    paddingHorizontal: 8,
    flexDirection: 'column',
    alignItems: 'flex-start',
    alignSelf: 'stretch',
    borderRadius: 16,
    backgroundColor: '#F9FAFB',
    shadowColor: '#181E25',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    marginBottom: 10,
    width: 350
  },
  sectionTitle: {
    fontSize: 20,
    marginBottom: 1,
  },
  headerContainer: {
    marginBottom: 20, 
    backgroundColor: 'white',
    width: 100,
  },
  mainContainer: {
    flex: 1,
    marginTop:15,
    marginLeft: 22,
    marginRight: 22
  },
  containerGame:{
    flex: 1,
    width: 370,
    marginRight: 60
  },
  tableHeader: {
    flexDirection: 'row',    
    backgroundColor: '#e0e5eb',
    justifyContent: 'center',
    alignItems: 'center', 
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    width: '100%', 
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    width: '100%', 
    maxWidth: 500, 
    alignSelf: 'center', 
  },
  tableCell: {
    flex: 1,
    textAlign: 'center',
    paddingHorizontal: 5,
    fontWeight: 'bold',
    fontSize: 12,
    height: 25,  
    paddingTop: 7,
    color:'#5D6D7D'
  },
  pointsCell: {
    flex: 2,
    textAlign: 'center',
    paddingHorizontal: 5,
  },
  DeclaringCell: {
    fontSize: 12,
    flex: 1.5,
    textAlign: 'center',
    paddingHorizontal: 5
  },
  scrollView: {
    flexGrow: 1,
    width: '100%',
    maxWidth: 500,
    maxHeight: 500,
  },
  scrollViewBouton:{
    flexGrow: 1,
    width: '100%', 
    maxWidth: 500,
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  boardListContainer: {
    borderRadius: 30,  
    backgroundColor:'white'
  },
  Gamecontainer:{
    flex: 1,
    alignItems: 'center', 
    backgroundColor: 'white', 
    width: '100%', 
    maxWidth: '100%',
    alignSelf: 'center', 
  },
  donnecell: {
    fontSize: 12,
    flex: 1,
    textAlign: 'center',
    paddingHorizontal: 5
  },
  headerlayout: {
    fontSize: 15,
    height:110,
    backgroundColor:"#009db7",
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,  
  },
  texttopheader: {
    textAlign: 'center',
    marginLeft: 30,
    fontFamily: 'Nexa', 
    fontSize: 18, 
    fontWeight: 'bold',
  },
  layoutIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    marginLeft: 25,
    marginTop:55  },
  textbottomheader: {
    textAlign: 'center',
    color: '#FFF', 
    fontFamily: 'Nexa', 
    fontSize: 18,
    fontStyle: 'normal', 
    fontWeight: '700', 
    lineHeight: 22, 
  },
  iconlayout: {
    marginHorizontal: 20,
    color: '#FFF',
  },
  ButtonSheet: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginLeft: 65, 
    marginTop: 40,
  },
  AddDonne: {
    color: '#3E4C5D', 
    textAlign: 'center', 
    fontFamily: 'Nexa', 
    fontSize: 16, 
    fontStyle: 'normal',
    fontWeight: '700', 
    lineHeight: 22, // Hauteur de ligne en pixels (137.5% de 16px)
    textDecorationLine: 'underline', 
    marginTop: 10,
    marginLeft: 40
  },
  BackDonne: {
    textAlign: 'center',
    fontFamily: 'Nexa', 
    fontSize: 16, 
    fontStyle: 'normal',
    fontWeight: '700', 
    lineHeight: 22, // Hauteur de ligne en pixels (137.5% de 16px)
    color: '#3E4C5D',
    marginLeft: 60,
    justifyContent: 'center',
    marginBottom: 10,
    alignItems: 'center',
  },
  separator: {
    height: 1,
    backgroundColor: 'gray', 
    marginVertical: 10, 
  },
  currentGameContainer: {
    flexDirection: 'row',
    textAlign: 'center', 
    justifyContent: 'center',
  },
  DeleteSelected: {
    color: 'white',
    backgroundColor: 'red',
    padding: 10,
    textAlign: 'center',
    borderRadius: 5,
    margin: 10,
  },
  boardListHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#f5f5f5',
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  modalContainerGame: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius:30 
  },
  modalContent: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    width: '80%',
    alignItems: 'center',
  },
  modalHeaderText: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    padding: 10,
    width: '100%',
    marginBottom: 20,
  },
  modalButtonEditGame: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
  },
  modalButton: {
    padding: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ccc',
    width: '40%',
    alignItems: 'center',
  },
  modalButtonTextCancel: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  modalButtonTextSave: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'blue'
  },
});